world-federation-of-advertisers/virtual-people-core-serving

WORKSPACE, src/main/cc/wfa/virtual_people/core/model/utils/BUILD.bazel, src/main/cc/wfa/virtual_people/core/model/utils/distributed_consistent_hashing.cc, src/main/cc/wfa/virtual_people/core/model/utils/distributed_consistent_hashing.h, src/main/cc/wfa/virtual_people/core/model/utils/distributed_consistent_hashing_test.cc
The details of the algorithm and the original Python implementation can
be found in
https://github.com/world-federation-of-advertisers/virtual_people_examples/blob/main/notebooks/Consistent_Hashing.ipynb.
=> Create C++ implementation of consistent hashing for distributions.

WORKSPACE, src/main/cc/wfa/virtual_people/core/labeler/BUILD.bazel, src/main/cc/wfa/virtual_people/core/labeler/labeler.cc, src/main/cc/wfa/virtual_people/core/labeler/labeler.h, src/main/cc/wfa/virtual_people/core/labeler/labeler_test.cc, src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, src/main/cc/wfa/virtual_people/core/model/branch_node_impl.h, src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc, src/main/cc/wfa/virtual_people/core/model/model_node.cc, src/main/cc/wfa/virtual_people/core/model/model_node.h, src/main/cc/wfa/virtual_people/core/model/population_node_impl.h
Remove the method to resolve child reference in ModelNode, which will be handled in ModelNode::Build.
Implement Labeler API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/11)
=> Create Labeler API

WORKSPACE, src/main/cc/wfa/virtual_people/core/model/attributes_updater/BUILD.bazel, src/main/cc/wfa/virtual_people/core/model/attributes_updater/attributes_updater.cc, src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_assignment_impl.cc, src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_assignment_impl.h, src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_assignment_impl_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/12)
=> Implement conditional_assignment.

src/main/cc/wfa/virtual_people/core/model/update_tree_impl_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/14)
=> Remove trailing space.

.github/workflows/build-test.yml, .github/workflows/lint.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/16)
=> Add GitHub actions to lint and run Bazel tests

src/main/cc/wfa/virtual_people/core/labeler/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/17)
=> Make Labeler visible publicly.

WORKSPACE, src/main/cc/wfa/virtual_people/core/labeler/labeler.h, src/main/cc/wfa/virtual_people/core/model/attributes_updater.cc, src/main/cc/wfa/virtual_people/core/model/attributes_updater.h, src/main/cc/wfa/virtual_people/core/model/branch_node_impl.h, src/main/cc/wfa/virtual_people/core/model/conditional_assignment_impl.h, src/main/cc/wfa/virtual_people/core/model/conditional_merge_impl.h, src/main/cc/wfa/virtual_people/core/model/model_node.cc, src/main/cc/wfa/virtual_people/core/model/model_node.h, src/main/cc/wfa/virtual_people/core/model/population_node_impl.h, src/main/cc/wfa/virtual_people/core/model/sparse_update_matrix_impl.h, src/main/cc/wfa/virtual_people/core/model/stop_node_impl.h, src/main/cc/wfa/virtual_people/core/model/update_matrix_impl.h, src/main/cc/wfa/virtual_people/core/model/update_tree_impl.h, src/main/cc/wfa/virtual_people/core/model/utils/consistent_hash.cc, src/main/cc/wfa/virtual_people/core/model/utils/consistent_hash.h, src/main/cc/wfa/virtual_people/core/model/utils/constants.h, src/main/cc/wfa/virtual_people/core/model/utils/distributed_consistent_hashing.h, src/main/cc/wfa/virtual_people/core/model/utils/field_filters_matcher.h, src/main/cc/wfa/virtual_people/core/model/utils/hash_field_mask_matcher.h, src/main/cc/wfa/virtual_people/core/model/utils/update_matrix_helper.h, src/main/cc/wfa/virtual_people/core/model/utils/virtual_person_selector.cc, src/main/cc/wfa/virtual_people/core/model/utils/virtual_person_selector.h, src/test/cc/wfa/virtual_people/core/model/BUILD.bazel, src/test/cc/wfa/virtual_people/core/model/conditional_assignment_impl_test.cc
Apply clang-format on C++ files.
Fix #ifndef macros.
Update the version of common-cpp and virtual-people-common.
Do not merge until https://github.com/world-federation-of-advertisers/virtual-people-common/pull/20 is merged and the TODO in WORKSPACE is resolved.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/21)
=> Code style fix.

src/main/cc/wfa/virtual_people/core/labeler/BUILD.bazel, src/main/cc/wfa/virtual_people/core/model/BUILD.bazel, src/main/cc/wfa/virtual_people/core/model/population_node_impl.cc, src/main/cc/wfa/virtual_people/core/model/utils/virtual_person_selector.h, src/test/cc/wfa/virtual_people/core/model/BUILD.bazel, src/test/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc, src/test/cc/wfa/virtual_people/core/model/conditional_assignment_impl_test.cc, src/test/cc/wfa/virtual_people/core/model/population_node_impl_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/22)
=> Set virtual person activities in PopulationNode.

src/main/cc/wfa/virtual_people/core/model/utils/distributed_consistent_hashing.cc, src/test/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc, src/test/cc/wfa/virtual_people/core/model/sparse_update_matrix_impl_test.cc, src/test/cc/wfa/virtual_people/core/model/update_matrix_impl_test.cc, src/test/cc/wfa/virtual_people/core/model/utils/distributed_consistent_hashing_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/23)
=> Return error status when the probabilities are not normalized.

src/main/cc/wfa/virtual_people/core/model/population_node_impl.cc, src/main/cc/wfa/virtual_people/core/model/population_node_impl.h, src/test/cc/wfa/virtual_people/core/model/population_node_impl_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/24)
=> Do not set virtual person id when the node is an empty population pool.

WORKSPACE, src/main/cc/wfa/virtual_people/core/model/population_node_impl.cc, src/test/cc/wfa/virtual_people/core/model/population_node_impl_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/27)
=> Set label from label/quantum_label in population node.

src/test/cc/wfa/virtual_people/core/test_data/toy_model.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/28)
=> add toy model config

WORKSPACE, src/main/cc/wfa/virtual_people/core/labeler/labeler.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/35)
=> Set the fingerprint for logged in/out user infos.

src/main/cc/wfa/virtual_people/core/model/BUILD.bazel, src/main/cc/wfa/virtual_people/core/model/model_serializer.cc, src/main/cc/wfa/virtual_people/core/model/model_serializer.h, src/main/cc/wfa/virtual_people/model_writer/BUILD.bazel, src/main/cc/wfa/virtual_people/model_writer/model_writer_main.cc, src/test/cc/wfa/virtual_people/core/model/BUILD.bazel, src/test/cc/wfa/virtual_people/core/model/model_serializer_test.cc
This tool takes a model in single node representation, converts to
node list representation, then write to file in Riegeli format.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/46)
=> Add a tool that converts VID model to node list representation.

WORKSPACE
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/47)
=> Update the common-cpp and virtual-people-common version.

src/main/cc/wfa/virtual_people/core/model/BUILD.bazel, src/main/cc/wfa/virtual_people/core/model/model_serializer.cc, src/main/cc/wfa/virtual_people/model_writer/BUILD.bazel, src/test/cc/wfa/virtual_people/core/labeler/BUILD.bazel, src/test/cc/wfa/virtual_people/core/model/BUILD.bazel, src/test/cc/wfa/virtual_people/core/model/model_serializer_test.cc, src/test/cc/wfa/virtual_people/core/model/multiplicity_impl_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/50)
=> Remove unused code and fix build dependencies.

src/main/kotlin/org/wfanet/virtualpeople/core/model/utils/BUILD.bazel, src/main/kotlin/org/wfanet/virtualpeople/core/model/utils/ConsistentHash.kt, src/test/cc/wfa/virtual_people/core/model/utils/consistent_hash_test.cc, src/test/kotlin/org/wfanet/virtualpeople/core/model/utils/BUILD.bazel, src/test/kotlin/org/wfanet/virtualpeople/core/model/utils/ConsistentHashTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/53)
=> Implement the kotlin jumpConsistentHash method.

src/main/kotlin/org/wfanet/virtualpeople/core/model/utils/BUILD.bazel, src/main/kotlin/org/wfanet/virtualpeople/core/model/utils/DistributedConsistentHashing.kt, src/test/cc/wfa/virtual_people/core/model/utils/distributed_consistent_hashing_test.cc, src/test/kotlin/org/wfanet/virtualpeople/core/model/utils/BUILD.bazel, src/test/kotlin/org/wfanet/virtualpeople/core/model/utils/DistributedConsistentHashingTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/54)
=> Implement the kotlin DistributedConsistentHashing

build/repositories.bzl, src/main/kotlin/org/wfanet/virtualpeople/core/model/utils/BUILD.bazel, src/main/kotlin/org/wfanet/virtualpeople/core/model/utils/FieldFiltersMatcher.kt, src/test/kotlin/org/wfanet/virtualpeople/core/model/utils/BUILD.bazel, src/test/kotlin/org/wfanet/virtualpeople/core/model/utils/FieldFiltersMatcherTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/55)
=> Implement the kotlin FieldFiltersMatcher class.

src/main/kotlin/org/wfanet/virtualpeople/core/model/utils/BUILD.bazel, src/main/kotlin/org/wfanet/virtualpeople/core/model/utils/HashFieldMaskMatcher.kt, src/test/kotlin/org/wfanet/virtualpeople/core/model/utils/BUILD.bazel, src/test/kotlin/org/wfanet/virtualpeople/core/model/utils/HashFieldMaskMatcherTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/56)
=> Implement the kotlin HashFieldMaskMatcher class.

src/main/kotlin/org/wfanet/virtualpeople/core/model/utils/UpdateMatrixHelper.kt, src/main/kotlin/org/wfanet/virtualpeople/core/model/utils/VirtualPeopleSelector.kt, src/test/cc/wfa/virtual_people/core/model/utils/virtual_person_selector_test.cc, src/test/kotlin/org/wfanet/virtualpeople/core/model/utils/BUILD.bazel, src/test/kotlin/org/wfanet/virtualpeople/core/model/utils/UpdateMatrixHelperTest.kt, src/test/kotlin/org/wfanet/virtualpeople/core/model/utils/VirtualPeopleSelectorTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/57)
=> Implement the VirtualPeopleSelector class and SelectFromMatrix().

build/repositories.bzl, src/main/kotlin/org/wfanet/virtualpeople/core/model/AttributesUpdaterInterface.kt, src/main/kotlin/org/wfanet/virtualpeople/core/model/BUILD.bazel, src/main/kotlin/org/wfanet/virtualpeople/core/model/ModelNode.kt, src/main/kotlin/org/wfanet/virtualpeople/core/model/UpdateMatrixImpl.kt, src/test/cc/wfa/virtual_people/core/model/update_matrix_impl_test.cc, src/test/kotlin/org/wfanet/virtualpeople/core/model/BUILD.bazel, src/test/kotlin/org/wfanet/virtualpeople/core/model/UpdateMatrixImplTest.kt
Required interfaces are also defined.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/58)
=> Implement the UpdateMatrixImpl class.

src/main/kotlin/org/wfanet/virtualpeople/core/model/AttributesUpdaterInterface.kt, src/main/kotlin/org/wfanet/virtualpeople/core/model/BUILD.bazel, src/main/kotlin/org/wfanet/virtualpeople/core/model/SparseUpdateMatrixImpl.kt, src/main/kotlin/org/wfanet/virtualpeople/core/model/UpdateMatrixImpl.kt, src/test/cc/wfa/virtual_people/core/model/sparse_update_matrix_impl_test.cc, src/test/kotlin/org/wfanet/virtualpeople/core/model/BUILD.bazel, src/test/kotlin/org/wfanet/virtualpeople/core/model/SparseUpdateMatrixImplTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/59)
=> Implememnt the kotlin SparseUpdateMatrixImpl class.

src/main/kotlin/org/wfanet/virtualpeople/core/model/AttributesUpdaterInterface.kt, src/main/kotlin/org/wfanet/virtualpeople/core/model/BUILD.bazel, src/main/kotlin/org/wfanet/virtualpeople/core/model/ConditionalAssignmentImpl.kt, src/test/kotlin/org/wfanet/virtualpeople/core/model/BUILD.bazel, src/test/kotlin/org/wfanet/virtualpeople/core/model/ConditionalAssignmentImplTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/60)
=> Implement the kotlin ConditionalAssignmentImpl class.

src/main/kotlin/org/wfanet/virtualpeople/core/model/AttributesUpdaterInterface.kt, src/main/kotlin/org/wfanet/virtualpeople/core/model/BUILD.bazel, src/main/kotlin/org/wfanet/virtualpeople/core/model/ConditionalMergeImpl.kt, src/main/kotlin/org/wfanet/virtualpeople/core/model/utils/FieldFiltersMatcher.kt, src/test/kotlin/org/wfanet/virtualpeople/core/model/BUILD.bazel, src/test/kotlin/org/wfanet/virtualpeople/core/model/ConditionalMergeImplTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/61)
=> Implement the kotlin ConditionalMergeImpl class.

src/main/kotlin/org/wfanet/virtualpeople/core/model/BUILD.bazel, src/main/kotlin/org/wfanet/virtualpeople/core/model/MultiplicityImpl.kt, src/test/cc/wfa/virtual_people/core/model/multiplicity_impl_test.cc, src/test/kotlin/org/wfanet/virtualpeople/core/model/BUILD.bazel, src/test/kotlin/org/wfanet/virtualpeople/core/model/MultiplicityImplTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/62)
=> Implement the kotlin MultiplicityImpl class.

src/main/kotlin/org/wfanet/virtualpeople/core/model/BUILD.bazel, src/main/kotlin/org/wfanet/virtualpeople/core/model/ModelNode.kt, src/main/kotlin/org/wfanet/virtualpeople/core/model/StopNodeImpl.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/64)
=> StopNode Implementation

build/repositories.bzl, src/main/kotlin/org/wfanet/virtualpeople/core/model/BUILD.bazel, src/main/kotlin/org/wfanet/virtualpeople/core/model/BranchNodeImpl.kt, src/main/kotlin/org/wfanet/virtualpeople/core/model/ModelNode.kt, src/main/kotlin/org/wfanet/virtualpeople/core/model/MultiplicityImpl.kt, src/main/kotlin/org/wfanet/virtualpeople/core/model/PopulationNodeImpl.kt, src/test/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc, src/test/kotlin/org/wfanet/virtualpeople/core/model/BUILD.bazel, src/test/kotlin/org/wfanet/virtualpeople/core/model/BranchNodeImplTest.kt, src/test/kotlin/org/wfanet/virtualpeople/core/model/ConditionalMergeImplTest.kt, src/test/kotlin/org/wfanet/virtualpeople/core/model/PopulationNodeImplTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/65)
=> Implement the kotlin BranchNodeImpl class.

src/main/kotlin/org/wfanet/virtualpeople/core/model/AttributesUpdaterInterface.kt, src/main/kotlin/org/wfanet/virtualpeople/core/model/BUILD.bazel, src/main/kotlin/org/wfanet/virtualpeople/core/model/UpdateTreeImpl.kt, src/test/kotlin/org/wfanet/virtualpeople/core/model/BUILD.bazel, src/test/kotlin/org/wfanet/virtualpeople/core/model/UpdateTreeImplTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/66)
=> Implement the kotlin UpdateTreeImpl class.

src/main/kotlin/org/wfanet/virtualpeople/core/labeler/Labeler.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/69)
=> Mark the labeler.build() methods JvmStatic

src/main/cc/wfa/virtual_people/core/model/population_node_impl.cc, src/test/cc/wfa/virtual_people/core/model/population_node_impl_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/71)
=> Remove support for empty pool and add check for cookie monster pool.

src/main/kotlin/org/wfanet/virtualpeople/core/model/AttributesUpdaterInterface.kt, src/main/kotlin/org/wfanet/virtualpeople/core/model/BUILD.bazel, src/main/kotlin/org/wfanet/virtualpeople/core/model/GeometricShredderImpl.kt, src/main/kotlin/org/wfanet/virtualpeople/core/model/utils/Hash.kt, src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc, src/test/kotlin/org/wfanet/virtualpeople/core/model/BUILD.bazel, src/test/kotlin/org/wfanet/virtualpeople/core/model/GeometricShredderImplTest.kt
Add Kotlin implementation of GeometricShredder.
=> Add Kotlin implementation of GeometricShredder.
